// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
// ---------------------------------------------------------------------------
package com.kl.comp.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

public interface IPublicMCComp {

  /**
   * Provides access to the generic API of this component.
   */
  IWDComponent wdGetAPI();


  /**
   * Interface for the node 'Context'.
   *
   * singleton = true, cardinality = _1_1, selection = _1_1
   */
  public static class IContextNode extends Node
  {
    private InternalMCComp gen_delegate;

    IContextNode(InternalMCComp delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    protected com.sap.tc.webdynpro.progmodel.context.Node createNode(IGCINodeInfo nodeInfo, com.sap.tc.webdynpro.progmodel.context.Node parentNode, com.sap.tc.webdynpro.progmodel.context.NodeElement parentElement) {
      if (nodeInfo == gen_delegate.infoContext)
        return new IPrivateMCComp.IContextNode(gen_delegate, nodeInfo, parentNode);
      if (nodeInfo == gen_delegate.infoAclUser)
        return new IPrivateMCComp.IAclUserNode(gen_delegate, nodeInfo, parentNode);
      if (nodeInfo == gen_delegate.infoAvailableCountriesList)
        return new IPrivateMCComp.IAvailableCountriesListNode(gen_delegate, nodeInfo, parentNode);
      if (nodeInfo == gen_delegate.infoAclUserCountriesList)
        return new IPrivateMCComp.IAclUserCountriesListNode(gen_delegate, nodeInfo, parentNode);
      return super.createNode(nodeInfo, parentNode, parentElement);
    }

    protected com.sap.tc.webdynpro.progmodel.context.NodeElement doCreateElement(IGCINodeInfo nodeInfo, Object reference) {
      if (nodeInfo == gen_delegate.infoContext) {
        return new IPrivateMCComp.IContextElement(gen_delegate, nodeInfo);
      }
      if (nodeInfo == gen_delegate.infoAclUser) {
        return new IPrivateMCComp.IAclUserElement(gen_delegate, nodeInfo, reference);
      }
      if (nodeInfo == gen_delegate.infoAvailableCountriesList) {
        return new IPrivateMCComp.IAvailableCountriesListElement(gen_delegate, nodeInfo, reference);
      }
      if (nodeInfo == gen_delegate.infoAclUserCountriesList) {
        return new IPrivateMCComp.IAclUserCountriesListElement(gen_delegate, nodeInfo, reference);
      }
      return super.doCreateElement(nodeInfo, reference);
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Provides access to the generic context API as described by IWDContext.
     */
    public IWDContext wdGetAPI() {
      return getContext();
    }

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IContextElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @return an element for this node
     */
    public IPrivateMCComp.IContextElement createContextElement() {
      return (IPrivateMCComp.IContextElement)createElement();
    }

    /**
     * Binds a single IContextElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateMCComp.IContextElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateMCComp.IContextElement currentContextElement() {
      return (IPrivateMCComp.IContextElement) getCurrentElement();
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

    private IPrivateMCComp.IAclUserNode gen_nodeAclUser;
    
    /**
     * Returns the singleton child node AclUser.
     * @return the child node
     */
    public IPrivateMCComp.IAclUserNode nodeAclUser() {
      if (gen_nodeAclUser == null)
        gen_nodeAclUser = (IPrivateMCComp.IAclUserNode) getChildNode("AclUser");
      return gen_nodeAclUser;
    }

    /**
     * Returns the current (lead selection) element of the singleton child node
     * AclUser.
     * @return the child node element or <code>null</code> if no such element 
     *         exists
     */
    public IPrivateMCComp.IAclUserElement currentAclUserElement() {
      return (IPrivateMCComp.IAclUserElement) nodeAclUser().getCurrentElement();
    }

    public IPrivateMCComp.IAclUserElement createAclUserElement(com.kl.bean.CountryDao model) {
      return (IPrivateMCComp.IAclUserElement) doCreateElement(gen_delegate.infoAclUser, model);
    }

    /**
     * Returns the descendant node AvailableCountriesList that is on the lead selection path.
     * @return the descendant node
     */
    public IPrivateMCComp.IAvailableCountriesListNode nodeAvailableCountriesList() {
      IPrivateMCComp.IAclUserNode node = nodeAclUser();
      return (IPrivateMCComp.IAvailableCountriesListNode)(node != null ? node.getChildNode("AvailableCountriesList", LEAD_SELECTION) : null);
    }

    /**
     * Returns the current (lead selection) element of the descendant node AvailableCountriesList 
     * following the lead selection path to that node.
     * @return the lead selection element of the descendant node 
     */
    public IPrivateMCComp.IAvailableCountriesListElement currentAvailableCountriesListElement() {
      IPrivateMCComp.IAvailableCountriesListNode node = nodeAvailableCountriesList();
      return (IPrivateMCComp.IAvailableCountriesListElement)(node != null ? node.getCurrentElement() : null);
    }

    /**
     * Creates a new, unbound element for the descendant node AvailableCountriesList. 
     * @return the newly created element 
     */
    public IPrivateMCComp.IAvailableCountriesListElement createAvailableCountriesListElement(com.kl.bean.CountryBean model) {
      return (IPrivateMCComp.IAvailableCountriesListElement) nodeAvailableCountriesList().createElement(model);
    }

    /**
     * Returns the descendant node AclUserCountriesList that is on the lead selection path.
     * @return the descendant node
     */
    public IPrivateMCComp.IAclUserCountriesListNode nodeAclUserCountriesList() {
      IPrivateMCComp.IAclUserNode node = nodeAclUser();
      return (IPrivateMCComp.IAclUserCountriesListNode)(node != null ? node.getChildNode("AclUserCountriesList", LEAD_SELECTION) : null);
    }

    /**
     * Returns the current (lead selection) element of the descendant node AclUserCountriesList 
     * following the lead selection path to that node.
     * @return the lead selection element of the descendant node 
     */
    public IPrivateMCComp.IAclUserCountriesListElement currentAclUserCountriesListElement() {
      IPrivateMCComp.IAclUserCountriesListNode node = nodeAclUserCountriesList();
      return (IPrivateMCComp.IAclUserCountriesListElement)(node != null ? node.getCurrentElement() : null);
    }

    /**
     * Creates a new, unbound element for the descendant node AclUserCountriesList. 
     * @return the newly created element 
     */
    public IPrivateMCComp.IAclUserCountriesListElement createAclUserCountriesListElement(com.kl.bean.CountryBean model) {
      return (IPrivateMCComp.IAclUserCountriesListElement) nodeAclUserCountriesList().createElement(model);
    }

  }

  /**
   * Interface for the elements of the node Context.
   */
  public static class IContextElement extends com.sap.tc.webdynpro.progmodel.context.NodeElement
  {
    private InternalMCComp gen_delegate;

    public IContextElement(InternalMCComp delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info) {
      super(info);
      gen_delegate = delegate;
    }

  }


  /**
   * Interface for the node 'AclUser'.
   *
   * singleton = true, cardinality = _0_n, selection = _0_1
   */
  public static class IAclUserNode extends Node
  {
    private InternalMCComp gen_delegate;

    IAclUserNode(InternalMCComp delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IAclUserElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @param model an instance of com.kl.bean.CountryDao needed for this model element
     * @return an element for this node
     */
    public IPrivateMCComp.IAclUserElement createAclUserElement(com.kl.bean.CountryDao model) {
      return (IPrivateMCComp.IAclUserElement)createElement(model);
    }

    /**
     * Binds a single IAclUserElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateMCComp.IAclUserElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /**
     * Creates a new IAclUserElement with the given model object 
     * and binds it to this node.
     * @param model an object of the model class
     */
    public void bind(com.kl.bean.CountryDao model) {
      bind(model == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(model));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateMCComp.IAclUserElement currentAclUserElement() {
      return (IPrivateMCComp.IAclUserElement) getCurrentElement();
    }

    /** 
     * Returns the element at the given index.
     * @param index the index of the element you want to get
     * @return the element or <code>null</code> if no element
     *         exists at that index
     */
    public IPrivateMCComp.IAclUserElement getAclUserElementAt(int index) {
      return (IPrivateMCComp.IAclUserElement) getElementAt(index);
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

    private IPrivateMCComp.IAvailableCountriesListNode gen_nodeAvailableCountriesList;
    
    /**
     * Returns the singleton child node AvailableCountriesList.
     * @return the child node
     */
    public IPrivateMCComp.IAvailableCountriesListNode nodeAvailableCountriesList() {
      if (gen_nodeAvailableCountriesList == null)
        gen_nodeAvailableCountriesList = (IPrivateMCComp.IAvailableCountriesListNode) getChildNode("AvailableCountriesList");
      return gen_nodeAvailableCountriesList;
    }

    private IPrivateMCComp.IAclUserCountriesListNode gen_nodeAclUserCountriesList;
    
    /**
     * Returns the singleton child node AclUserCountriesList.
     * @return the child node
     */
    public IPrivateMCComp.IAclUserCountriesListNode nodeAclUserCountriesList() {
      if (gen_nodeAclUserCountriesList == null)
        gen_nodeAclUserCountriesList = (IPrivateMCComp.IAclUserCountriesListNode) getChildNode("AclUserCountriesList");
      return gen_nodeAclUserCountriesList;
    }

  }

  /**
   * Interface for the elements of the node AclUser.
   */
  public static class IAclUserElement extends com.sap.tc.webdynpro.progmodel.context.ModelNodeElement
  {
    private InternalMCComp gen_delegate;

    private final com.kl.bean.CountryDao gen_modelInstance;

    public IAclUserElement(InternalMCComp delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info, Object modelInstance) {
      super(info, modelInstance);
      this.gen_modelInstance = (com.kl.bean.CountryDao) modelInstance;
      gen_delegate = delegate;
    }

    /**
     * Returns the referenced com.kl.bean.CountryDao.
     * @return the referenced com.kl.bean.CountryDao
     */
    public com.kl.bean.CountryDao modelObject() {
      return gen_modelInstance;
    }

  }


  /**
   * Interface for the node 'AvailableCountriesList'.
   *
   * singleton = true, cardinality = _0_n, selection = _0_1
   */
  public static class IAvailableCountriesListNode extends Node
  {
    private InternalMCComp gen_delegate;

    IAvailableCountriesListNode(InternalMCComp delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IAvailableCountriesListElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @param model an instance of com.kl.bean.CountryBean needed for this model element
     * @return an element for this node
     */
    public IPrivateMCComp.IAvailableCountriesListElement createAvailableCountriesListElement(com.kl.bean.CountryBean model) {
      return (IPrivateMCComp.IAvailableCountriesListElement)createElement(model);
    }

    /**
     * Binds a single IAvailableCountriesListElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateMCComp.IAvailableCountriesListElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /**
     * Creates a new IAvailableCountriesListElement with the given model object 
     * and binds it to this node.
     * @param model an object of the model class
     */
    public void bind(com.kl.bean.CountryBean model) {
      bind(model == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(model));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateMCComp.IAvailableCountriesListElement currentAvailableCountriesListElement() {
      return (IPrivateMCComp.IAvailableCountriesListElement) getCurrentElement();
    }

    /** 
     * Returns the element at the given index.
     * @param index the index of the element you want to get
     * @return the element or <code>null</code> if no element
     *         exists at that index
     */
    public IPrivateMCComp.IAvailableCountriesListElement getAvailableCountriesListElementAt(int index) {
      return (IPrivateMCComp.IAvailableCountriesListElement) getElementAt(index);
    }

    // ---- hooks ------------------------------------------------------------

    protected void doSupplyElements() {
      IWDNodeElement element = getParentElement();
      // follow the role AvailableCountriesList with cardinality _0_n
      bind(((IPrivateMCComp.IAclUserElement)element).modelObject().getAvailableCountriesList());
    }

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node AvailableCountriesList.
   */
  public static class IAvailableCountriesListElement extends com.sap.tc.webdynpro.progmodel.context.ModelNodeElement
  {
    private InternalMCComp gen_delegate;

    private final com.kl.bean.CountryBean gen_modelInstance;

    public IAvailableCountriesListElement(InternalMCComp delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info, Object modelInstance) {
      super(info, modelInstance);
      this.gen_modelInstance = (com.kl.bean.CountryBean) modelInstance;
      gen_delegate = delegate;
    }

    /**
     * Returns the referenced com.kl.bean.CountryBean.
     * @return the referenced com.kl.bean.CountryBean
     */
    public com.kl.bean.CountryBean modelObject() {
      return gen_modelInstance;
    }

    // attribute "country"
    public final static String COUNTRY = "country";

    /**
     * Returns the attribute country.
     */
    public java.lang.String getCountry() {
      return gen_modelInstance.getCountry();
    }

    /**
     * Sets the attribute country.
     * @param value the new value
     */
    public void setCountry(java.lang.String value) {
      gen_modelInstance.setCountry(value);
      changed(0);
    }
    
    // attribute "countryCode"
    public final static String COUNTRY_CODE = "countryCode";

    /**
     * Returns the attribute countryCode.
     */
    public java.lang.String getCountryCode() {
      return gen_modelInstance.getCountryCode();
    }

    /**
     * Sets the attribute countryCode.
     * @param value the new value
     */
    public void setCountryCode(java.lang.String value) {
      gen_modelInstance.setCountryCode(value);
      changed(1);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // country
          return gen_modelInstance.getCountry();
        case 1: // countryCode
          return gen_modelInstance.getCountryCode();
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // country
          gen_modelInstance.setCountry((String)value);
          changed(info);
          break;
        case 1: // countryCode
          gen_modelInstance.setCountryCode((String)value);
          changed(info);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected String wdGetString(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // country
          return gen_modelInstance.getCountry();
        case 1: // countryCode
          return gen_modelInstance.getCountryCode();
        default:
          return super.wdGetString(info);
      }
    }

    protected void wdSetString(IGCIAttributeInfo info, String value) {
      switch (info.getIndex()) {
        case 0: // country
          gen_modelInstance.setCountry((java.lang.String)value);
          changed(info);
          break;
        case 1: // countryCode
          gen_modelInstance.setCountryCode((java.lang.String)value);
          changed(info);
          break;
        default:
          super.wdSetString(info, value);
          break;
      }
    }

  }


  /**
   * Interface for the node 'AclUserCountriesList'.
   *
   * singleton = true, cardinality = _0_n, selection = _0_1
   */
  public static class IAclUserCountriesListNode extends Node
  {
    private InternalMCComp gen_delegate;

    IAclUserCountriesListNode(InternalMCComp delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IAclUserCountriesListElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @param model an instance of com.kl.bean.CountryBean needed for this model element
     * @return an element for this node
     */
    public IPrivateMCComp.IAclUserCountriesListElement createAclUserCountriesListElement(com.kl.bean.CountryBean model) {
      return (IPrivateMCComp.IAclUserCountriesListElement)createElement(model);
    }

    /**
     * Binds a single IAclUserCountriesListElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateMCComp.IAclUserCountriesListElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /**
     * Creates a new IAclUserCountriesListElement with the given model object 
     * and binds it to this node.
     * @param model an object of the model class
     */
    public void bind(com.kl.bean.CountryBean model) {
      bind(model == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(model));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateMCComp.IAclUserCountriesListElement currentAclUserCountriesListElement() {
      return (IPrivateMCComp.IAclUserCountriesListElement) getCurrentElement();
    }

    /** 
     * Returns the element at the given index.
     * @param index the index of the element you want to get
     * @return the element or <code>null</code> if no element
     *         exists at that index
     */
    public IPrivateMCComp.IAclUserCountriesListElement getAclUserCountriesListElementAt(int index) {
      return (IPrivateMCComp.IAclUserCountriesListElement) getElementAt(index);
    }

    // ---- hooks ------------------------------------------------------------

    protected void doSupplyElements() {
      IWDNodeElement element = getParentElement();
      // follow the role AclUserCountriesList with cardinality _0_n
      bind(((IPrivateMCComp.IAclUserElement)element).modelObject().getAclUserCountriesList());
    }

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node AclUserCountriesList.
   */
  public static class IAclUserCountriesListElement extends com.sap.tc.webdynpro.progmodel.context.ModelNodeElement
  {
    private InternalMCComp gen_delegate;

    private final com.kl.bean.CountryBean gen_modelInstance;

    public IAclUserCountriesListElement(InternalMCComp delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info, Object modelInstance) {
      super(info, modelInstance);
      this.gen_modelInstance = (com.kl.bean.CountryBean) modelInstance;
      gen_delegate = delegate;
    }

    /**
     * Returns the referenced com.kl.bean.CountryBean.
     * @return the referenced com.kl.bean.CountryBean
     */
    public com.kl.bean.CountryBean modelObject() {
      return gen_modelInstance;
    }

    // attribute "country"
    public final static String COUNTRY = "country";

    /**
     * Returns the attribute country.
     */
    public java.lang.String getCountry() {
      return gen_modelInstance.getCountry();
    }

    /**
     * Sets the attribute country.
     * @param value the new value
     */
    public void setCountry(java.lang.String value) {
      gen_modelInstance.setCountry(value);
      changed(0);
    }
    
    // attribute "countryCode"
    public final static String COUNTRY_CODE = "countryCode";

    /**
     * Returns the attribute countryCode.
     */
    public java.lang.String getCountryCode() {
      return gen_modelInstance.getCountryCode();
    }

    /**
     * Sets the attribute countryCode.
     * @param value the new value
     */
    public void setCountryCode(java.lang.String value) {
      gen_modelInstance.setCountryCode(value);
      changed(1);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // country
          return gen_modelInstance.getCountry();
        case 1: // countryCode
          return gen_modelInstance.getCountryCode();
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // country
          gen_modelInstance.setCountry((String)value);
          changed(info);
          break;
        case 1: // countryCode
          gen_modelInstance.setCountryCode((String)value);
          changed(info);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected String wdGetString(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // country
          return gen_modelInstance.getCountry();
        case 1: // countryCode
          return gen_modelInstance.getCountryCode();
        default:
          return super.wdGetString(info);
      }
    }

    protected void wdSetString(IGCIAttributeInfo info, String value) {
      switch (info.getIndex()) {
        case 0: // country
          gen_modelInstance.setCountry((java.lang.String)value);
          changed(info);
          break;
        case 1: // countryCode
          gen_modelInstance.setCountryCode((java.lang.String)value);
          changed(info);
          break;
        default:
          super.wdSetString(info, value);
          break;
      }
    }

  }

  /**
   * Returns the context root node.
   * @return the context root node.
   */
  IContextNode wdGetContext();

}
